### ISSUE TITLE
Node was not found or was not executable

### ISSUE THREAD

**Issue by u840903** [jcartledge/sublime-worksheet#25] opened 2013-07-02 08:37 UTC
In Worksheet v0.7.3 on OSX 10.8.4 and ST2.0.1 thees lines of code result in an error.

Javascript:

``` javascript
var foo = function(bar){
    return bar;
}
foo('bar');
```

Console:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./worksheet.py", line 101, in run
  File "./worksheet.py", line 19, in run
  File "./repl/repl.py", line 8, in get_repl
  File "./repl/repl.py", line 42, in __init__
  File "./repl/pexpect.py", line 432, in __init__
  File "./repl/pexpect.py", line 519, in _spawn
repl.pexpect.ExceptionPexpect: The command was not found or was not executable: node.
```

**Comment by jcartledge** [comment] 2013-07-02 10:01
Thanks for the report. This looks like the same thing @CarettaCaretta reported at https://github.com/jcartledge/sublime-worksheet/issues/20#issuecomment-20284938.

I can't reproduce it here, so forgive me if I ask some obvious/stupid questions:
- Does node run in the terminal? What is the output of `node -v`?
- If yes, how did you install node? Homebrew, or another way?
- What is the output of `which node`?

Uh - not sure what else to look for at this point. We'll work this out, but I'm going to need your help.

**Comment by lpand** [comment] 2013-07-02 11:04
@jcartledge definitely `which('node')` returns None when `_spawn` is invoked, but from terminal

``` Python
> python
>>> import pexpect as pex
>>> pex.which('node')
'/usr/local/bin/node'
>>>
```

```
> node -v
v0.10.0
> which node
/usr/local/bin/node
```

If i remember correct i used [nave](https://github.com/isaacs/nave), `nave usemain latest` to install node.

Yesterday night it worked at some point, but today the problem is still there.

Thanks for your work, awesome plugin.

**Comment by timonwong** [comment] 2013-07-02 11:54
@CarettaCaretta 
<del>Because Sublime Text strip `/usr/local/bin` (at least) from `PATH` environment variable</del>(`/usr/local/bin` seems only accessible from terminal), so pexpect cannot find it.
You can change your `worksheet.sublime-settings` accordingly, in order to get it work:

``` json
        "JavaScript": {
            // Here we use absolute path for node
            "cmd": "/usr/local/bin/node -e \"require('repl').start('node> ')\"",
            "prompt": ["node> ", "\\.\\.+ "]
        }
```

**Comment by lpand** [comment] 2013-07-02 12:10
@timonwong 

i've checked, you're right and the solution works :satisfied:.
Thank you.

**Comment by jcartledge** [comment] 2013-07-02 12:23
That will work, but it would be better if you didn't have to hardcode it.

I'm not sure why, but /usr/local/bin is always in my path, no matter how I start ST - I thought maybe it made a difference if it was started from terminal rather than GUI, but not so.

I think it should be possible to append "/usr/local/bin" to `os.environ["PATH"]`. I'll check it out and see if it works so people don't have to hack their config to get it working.

**Comment by kosii** [comment] 2013-07-02 21:03
For me `/usr/local/bin` is on the path if I start Sublime from the terminal with `/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl`, but it's not present if Sublime is started by double-clicking on the Sublime application icon.

**Comment by u840903** [comment] 2013-07-02 22:26
Not sure if it's still of importance but I installed Node via Homebrew and it runs in the terminal.

```
> node -v
v0.10.12
> which node
/usr/local/bin/node
```

Happy to help!

**Comment by jcartledge** [comment] 2013-07-03 02:02
Does anyone who has this problem want check if the `path` branch resolves it? Thanks.

**Comment by jcartledge** [comment] 2013-07-03 06:30
I've merged my attempt at a fix for this into master but it's not in a release yet. I'm not going to close until someone can verify that it solves the problem for them.

**Comment by u840903** [comment] 2013-07-03 11:19
Path branch on OSX 10.8.4 and ST2.0.1 resolves the bug.

Javascript

```
var foo = function(bar){
    return bar;
}
foo('foobar');
```

Javascript after eval.

```
var foo = function(bar){
    return bar;
}
// > undefined

foo('foobar');
// > 'foobar'
```

**Comment by jcartledge** [comment] 2013-07-03 22:06
Great, thanks. I'll try to wrap it up today.

**Closed as completed** 2013-07-05 01:38 UTC
Labels: bug
