### ISSUE TITLE
Windows: scala: When I save file I get "Error: MoveFileEx(... .subl8be.tmp) c:\test.scala failed, Access is deined."

### ISSUE THREAD

**Issue by babusri** [jcartledge/sublime-worksheet#43] opened 2013-08-11 05:58 UTC
Using Windows 8.
When I save the scala file, I get this error.

Unable to save test.scala
Error: MoveFileEx(... .subl8be.tmp)
c:\test.scala failed, Access is deined.

**Note:** I got the same error when using scalaworksheet. I filed an issue and the plugin author Tony Sloane did some investigation.
https://bitbucket.org/inkytonik/scalaworksheet/issue/5/scalaworksheet-doesnt-work-on-windows

**Comment by timonwong** [comment] 2013-08-11 06:30
I assume you are using ST3, right? You can try turn of `atomic_save` in your sublime settings and see what happens:

``` javascript
{
    "atomic_save": false,
    // other settings...
}
```

Since worksheet plugin doesn't hold any lock on file (file contents are retrieved by sublime api), I think it may caused by other plugins, try a clean ST3 with other plugins disabled and see what happens).

**Comment by babusri** [comment] 2013-08-11 07:40
Timon Wong,
   Thanks for the prompt response. Yes, I was using ST3.
I switched to ST2 and it worked fine. Then it ST3 I set atomic_save to false and that too worked.

**Comment by jcartledge** [comment] 2013-08-14 00:50
Thanks Timon. OK to close this then?

**Comment by timonwong** [comment] 2013-08-15 14:38
@jcartledge 
Yes, should be an issue of "atomic_save".

**Closed as completed** 2013-08-16 01:40 UTC
